version: '3.9'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=gpt-oss:120b-cloud
    extra_hosts:
      - "host.docker.internal:host-gateway"
